### ISSUE TITLE
Using pv-tuning on other quantization methods

### ISSUE THREAD

**Issue by yaldashbz** [Vahe1994/AQLM#107]
Hi, could you please clarify what is `finetune_legacy.py` used for and what's the difference of it with `finetune_fsdp.py`?

Thanks

**Comment by Godofnothing** [comment]
Hi, @yaldashbz. 
* `finetune_legacy.py` - is the old finetuning code used in AQLM paper. It is inefficient, since it doesn't parallelize workload across multiple workers. Large models can be split across devices, but in sequential manner, where only 1 GPU is working at at time. This code is extremely slow for large enough dataset. 
 `finetune_fsdp.py` - is much more efficient version with data parallelism where one can tune both continious parameters (codebooks, norms, biases) and discrete - (codes). 
 
 Concering the question raised in the topic - current codebase provides pv-tuning for AQLM only.
