### ISSUE TITLE
Codebook size for LLama 2

### ISSUE THREAD

**Issue by Devy99** [Vahe1994/AQLM#117]
From the paper:  _"we used 1 codebook size of 2^15 or 2^16, with groups of 8 for 2 bits."_ 

Did you change the amount of codebooks based on the size of the LLama2 models? For example, did you use 2^15 for LLama 7B and 2^16 for LLama 70B? Or was the codebook size consistent across different sizes of the same model?

I'm asking because if we stick with the same configuration (1x15), the bpw varies among sizes. Improved codebook sizes also result in improved accuracy. Is it acceptable to compare a 1×15 schema of a smaller model to a 1×16 schema of a larger one, given the possibility of identical bpw?

**Comment by BlackSamorez** [comment]
> For example, did you use 2^15 for LLama 7B and 2^16 for LLama 70B?
Exactly. We did this because `2^16` would be closer to 2.3bpw for smaller models such as Llama 7b. For a fair comparison with other ~2bpw methods we opted for `2^15` codebook size which lands us at almost exactly 2bpw for those models.

As such, we think that the total bpw (including codebooks) is the best base for comparison, as described in Appendix H of [the paper](https://arxiv.org/pdf/2401.06118).

However, `2^15` doesn't make any sense in practical terms because the codes are still stored in `int16`, effectively using the same amount of memory as 2^16. So you should always do `1^16` (or `2^8`) for practical applications.

**Comment by Devy99** [comment]
Perfect, thanks!
