### ISSUE TITLE
AQLM does not work with OPT type models

### ISSUE THREAD

**Issue by ArtemBiliksin** [Vahe1994/AQLM#125]
Hello! 

AQLM does not work with `OPT` type models. The error occurs because of [line 114 in AQLM/main.py](https://github.com/Vahe1994/AQLM/blob/main/main.py#L114): namely because of the presence of `position_ids`. The error can be quickly detected by setting `val_size > 0`. I made a simple demo example in [collab](https://colab.research.google.com/drive/1qARZUQ79bji5ZNtD58ePQjbTKmg9htX6?usp=sharing). You can run it.

Below is a detailed description of the problem.

OPT type models have an [OPTDecoderLayer](https://github.com/huggingface/transformers/blob/main/src/transformers/models/opt/modeling_opt.py#L368) whose [forward](https://github.com/huggingface/transformers/blob/main/src/transformers/models/opt/modeling_opt.py#L386) method does not expect the `position_ids` parameter. [Line 220 of the AQLM/main.py](https://github.com/Vahe1994/AQLM/blob/main/main.py#L220) file will pass the OPTDecoderLayer to the `update_outs` function. The `update_outs` function calls ([line 542 of the AQLM/main.py file](https://github.com/Vahe1994/AQLM/blob/main/main.py#L542)) the OPTDecoderLayer with the passed data and key arguments from `forward_args`. The error ***TypeError: OPTDecoderLayer.forward() got an unexpected keyword argument position_ids*** will occur here, because the `forward_args` dictionary `contains` the `position_ids` keys, which is defined in line 114 of the AQLM/main.py file.

**Comment by Vahe1994** [comment]
Hi, @ArtemBiliksin!

Thanks for noticing this. We currently do not support OPT-type models due to low demand. I believe only a few lines of code would need to be changed to make it work with OPT models. If you have the time, you can create a PR with support for OPT models, and either I or my colleagues will review it. We're happy to accept any PR that improves the code.

Just a heads-up: the PR should not break compatibility with other models. Additionally, you'll need to provide an example of a successfully quantized OPT model to ensure everything works as expected.
