### ISSUE TITLE
Question about the number of bits contained in ‘codes’ in the paper

### ISSUE THREAD

**Issue by hyx1999** [Vahe1994/AQLM#132]
I'm studying the paper, but I'm having some difficulty with the part about calculating the number of bits included in the model.

My question is, in the paper, the number of bits in codes is $d_{out} * (d_{in}/g) * B$, but why not $d_{out} * (d_{in}/g) * B * M$?
![image](https://github.com/user-attachments/assets/d348bee5-7658-48d8-a423-6c1b65b20b43)

In "inference_lib/src/aqlm/inference.py", we also have
![image](https://github.com/user-attachments/assets/67483b68-aa63-44a0-938c-ffa0a3d96352)

**Comment by ArtemBiliksin** [comment]
Hello, @hyx1999 !

If we assume that here the value of $codes: d_{out} \cdot (d_{in} / g) \cdot B$ refers to the number of bits **per** book, then in general there is no contradiction. I asked the same question in [issue 122](https://github.com/Vahe1994/AQLM/issues/122). You are welcome to read it. There I showed that there was an error in the third version article. In the current fourth version, this error has been corrected. I think it would be clearer to add the multiplier M so that there is no question.

**Comment by hyx1999** [comment]
Thank you very much！ @ArtemBiliksin
