### ISSUE TITLE
A small inaccuracy in the metrics of the unquantized llama-2-7b model

### ISSUE THREAD

**Issue by ArtemBiliksin** [Vahe1994/AQLM#134]
Hello! 

In the AQLM (v4) paper, in Table 1 and Table 12, the values of PiQA, HellaSwag, ArcE, ArcC metrics are different for the unquantized llama-2-7b model. Is this the way it should be? It seems to me that it is a small error, because all other tables are correct.

![image](https://github.com/user-attachments/assets/7b0e991f-455b-4c5e-be62-f31c14bb2418)

**Comment by Vahe1994** [comment]
Hey @ArtemBiliksin, thanks for noticing this! Both numbers are correct. We remeasured the unquantized model for the camera-ready version of the paper, a few months after the initial measurements. Although we tried to keep the setup mostly the same as in the initial experiments, I think the small difference is due to some libraries being updated to newer versions.

**Comment by ArtemBiliksin** [comment]
Hi, @Vahe1994 ! Thanks for the reply!
