### ISSUE TITLE
Any chance to have K x 16 / 1 x 16 scheme implemented for Numba?

### ISSUE THREAD

**Issue by alex4321** [Vahe1994/AQLM#24]
Hi. I am interested in some ideas requiring Mixtral-type model & for resource purpose - quantization & partial CPU offloading.

So since it seems this quantization technique is relatively good - I am going to try it.

However, as far as I understand due to https://github.com/Vahe1994/AQLM/blob/main/README.md - the best result is achieved with 1x16 scheme and it is not implemented for CPU case (well, not optimized kernel - due to https://github.com/Vahe1994/AQLM/blob/main/inference_lib/src/aqlm/inference_kernels/kernel_selector.py it should do dequantization and torch built-in matmul on top of that).

So I guess I may later dive into implementing such a scheme, but maybe it's on plan anyway?

**Comment by BlackSamorez** [comment]
The approach we used for `Kx8` kernels will certainly not work due to limitations of the dot product precomputation subroutine we employed. It only makes sense for small codebooks (~8 bits).

One, however, could implement normal MatMul and, possibly, obtain speedup, but we haven't explored that direction. We're not currently working in that direction and we would welcome any help regarding the matter. So, if you feel like doing it, we'll be happy to assist you in that endeavor!
