### ISSUE TITLE
print Total number of parameters is incomplete. 

### ISSUE THREAD

**Issue by Minami-su** [Vahe1994/AQLM#58]
model:ISTA-DASLab/Mixtral-8x7B-Instruct-v0_1-AQLM-2Bit-1x16-hf
```
model = AutoModelForCausalLM.from_pretrained(base_model,
                                             trust_remote_code=True,
                                             attn_implementation="flash_attention_2",
                                             torch_dtype=torch.bfloat16,
                                             device_map="auto",
                                             low_cpu_mem_usage=True)
total_parameters = sum(p.numel() for p in model.parameters())

print(f"Total number of parameters: {total_parameters}")
```
output:
Total number of parameters: 6546853888

**Comment by Minami-su** [comment]
Mixtral-8x7B-Instruct-v0_1 has approximately 46 billion parameters, obviously the number of parameters being output here is incorrect

**Comment by BlackSamorez** [comment]
Since AQLM employs vector quantization, each codes parameter encodes 8 `fp16` weights of the uncompressed model for the 1x16 setup. On top of that, codebooks and scales also contribute a nontrivial number of parameters.
In the end. There really are ~6.5b parameters in `ISTA-DASLab/Mixtral-8x7B-Instruct-v0_1-AQLM-2Bit-1x16-hf`: some of them are `int16` codes encoding larger vectors, some of them serve more complicated roles.
To learn more about the representation, please refer to either the original [AQLM paper](https://arxiv.org/abs/2401.06118) or this nice [blogpost explanation](https://towardsdatascience.com/the-aqlm-quantization-algorithm-explained-8cf33e4a783e).

**Comment by Minami-su** [comment]
> Since AQLM employs vector quantization, each codes parameter encodes 8 `fp16` weights of the uncompressed model for the 1x16 setup. On top of that, codebooks and scales also contribute a nontrivial number of parameters. In the end. There really are ~6.5b parameters in `ISTA-DASLab/Mixtral-8x7B-Instruct-v0_1-AQLM-2Bit-1x16-hf`: some of them are `int16` codes encoding larger vectors, some of them serve more complicated roles. To learn more about the representation, please refer to either the original [AQLM paper](https://arxiv.org/abs/2401.06118) or this nice [blogpost explanation](https://towardsdatascience.com/the-aqlm-quantization-algorithm-explained-8cf33e4a783e).

https://github.com/huggingface/peft/issues/1594
