### ISSUE TITLE
DBRX Support

### ISSUE THREAD

**Issue by FanaticPythoner** [Vahe1994/AQLM#64]
Does the current AQLM version work for DBRX?

**Comment by justheuristic** [comment]
Hi! There is currently an issue with DBRX implementation. In short, you have to modify dbrx code to make it compatible.

More specifically, the issue is that DbrxExpertGLU stores weights directly as sub-parameters, without creating nn.Linear layers. The problem with this is that AQLM quantizes all linear layers.

If you want to quantize DBRX, the easiest way is to 
1. fork the model code
2. modify DbrxExpertGLU code to use nn.Linear instead of raw weights
   - Here's the specific problem: [modeling_dbrx.py#L760-L766](https://github.com/databricks/dbrx/blob/7cbcf4e/model/modeling_dbrx.py#L760-L766)
    - You should rewrite it to use linear layers, similar to [this class](https://github.com/huggingface/transformers/blob/7cbcf4e/src/transformers/models/mixtral/modeling_mixtral.py#L790)
4. convert parameters from the original model and save the new model type.

After that, you can run AQLM on the converted model.

If you want the resulting model to be usable with `transformers.AutoModelForCausalLM.from_pretrained`, you can achieve this in two ways:
* (the easy way) add the modified model code to the uploaded model, see [this example](https://huggingface.co/hpcai-tech/grok-1/blob/main/modeling_grok1.py) and [this tutorial](https://huggingface.co/docs/transformers/en/custom_models)
* (the hard way) convince the DBRX model owner to modify their own code with nn.Linear to make it compatible for everyone

**Comment by justheuristic** [comment]
@FanaticPythoner on a second thought, it looks like the community has done some of the work.

Take a look at this model conversion script: https://huggingface.co/databricks/dbrx-instruct/discussions/10#660566f14f41c0c7c0e54ab9

**Comment by FanaticPythoner** [comment]
This one seems to look good.

Doesn't it?

https://huggingface.co/SinclairSchneider/dbrx-instruct-quantization-fixed

**Comment by FanaticPythoner** [comment]
I've access to 8X L40S 48GB.
