### ISSUE TITLE
Can you please share the *end-to-end* quantization script+config (including data used) for each model you've already quantized? (particularly llama-3 and miqu - i.e. 70B models)

### ISSUE THREAD

**Issue by josephrocca** [Vahe1994/AQLM#98]
Hi, this is a surprisingly underrated project - really valuable for the local LLM community where most people only have 24GB and can't quite run 70B models with reasonable quality. I've tested against GPTQ and it's competitive in my own evals. Obviously quants are much more expensive which is a slight bummer, but I think it's fine because there aren't that many *popular* 70B models that need to be converted. Still, there are a lot more than the ones that you've currently converted.

Given that you've already put together the script + data for Miqu and Llama 3, can you please share the "end-to-end" working scripts so people like myself who have compute/money to burn can try creating a quant starting from a "known good" config/dataset? I understand that the dataset may need some tweaking depending on the model, but having the initial starting point would be very handy. The *most ideal* approach imo would be a published Docker image that people can spin up on Runpod and just set an input path to existing model on HF + dataset. I'd be willing to spend several thousand converting a few popular models if it were that easy and the pre-made recipe was likely to work.

I'm only guessing, and my reasoning may be motivated by my own desire to play around with this without spending a lot of compute/money debugging it (because I undoubtedly will make mistakes even with well-written guides), but if you could share end-to-end working scripts, I think there's the potential for this project to get significantly more traction than it currently is. Relatively few people in the Local LLM scene use the vanilla versions of models, so the quants you've currently published aren't going to get much attention imo. The community could help here if you make it easy!

**Comment by Vahe1994** [comment]
Hi!

Thank you for your interest in the project and for your kind words. I'm more than happy to assist anyone who wants to help to quantize the new models (they are releasing too fast).

If I understand you correctly, you are asking for:
1. Scripts to do quantization end-to-end.
2. Configuration for models.
3. A Docker file/image for the environment.

Let see:
1. For the scripts, following these links in succession is enough: [How to Quantize a Model with AQLM](https://github.com/Vahe1994/AQLM?tab=readme-ov-file#how-to-quantize-a-model-with-aqlm), [Finetuning](https://github.com/Vahe1994/AQLM?tab=readme-ov-file#finetuning), and finally [Preparing Models for Inference](https://github.com/Vahe1994/AQLM?tab=readme-ov-file#preparing-models-for-inference). In the end, you will get a quantized model in HF style.
2. I will share the config for LLama3 models here, so you can extrapolate for others. Hyperparameters do not need much tweaking between models.
3. I will think about this. The problem is that both our code, HF models, and the environment are changing rapidly, so a Docker file/image would need to be constantly updated to stay relevant.

There are some parameters, such as the number of codebooks and codebook size, that need to be set by the user manually because these define the bit levels you want to convert your model to. The popular supported ones are 2x8gs8 and 1x16gs8. You can see them in the [README](https://github.com/Vahe1994/AQLM#models).

I will think the way to make the process more painless or even make it more automatic("end-to-end" ), but this will make some time. Maybe first step is to just combine 3 scripts into 1 in bash file.  Meanwhile I encourage you to try 3 scripts described in 1-st point in succession and see maybe it is enough. There shouldn't be much debugging required(if any). However, I cannot guarantee this. If you have any issues, we will be more than happy to help.

P.S. FYI, there is a new paper from our team that improves AQLM quantization results with improved fine-tuning: [https://arxiv.org/pdf/2405.14852](https://arxiv.org/pdf/2405.14852). The team is actively working to merge it to the main branch and make it more accessible, but it will take some time.

**Comment by josephrocca** [comment]
> I will share the config for Llama3 models here

Thank you! Could you also share config for the other two 70B models - i.e. Llama-2-70b and Miqu (I'm guessing config may be the same for those two?)

A Dockerfile would be great, but some full/complete example scripts/config would get me 90% of the way there (in terms of confidence in spending the compute to try my hand at this).

Also, PV-Tuning looks very exciting - I'm looking forward to testing it too!

**Comment by justheuristic** [comment]
Hi, @josephrocca 
Vahe is a bit overworked atm, I will try to put together sample scripts for typical 7B and 70B models. Please note that the scripts 

For 7B models, the full calibration + finetuning + export + eval script can be done by running this (steps 1-5):
https://github.com/Vahe1994/AQLM/tree/pv-tuning?tab=readme-ov-file#1-initial-model-calibration

<details> <summary>For 70B models, the script would look roughly similar:</summary>

Environment variables:
```
export MODEL_PATH=meta-llama/Meta-Llama-3-70B
# ^--base model that you intend to quantize
export SEQLEN=8192
# ^-- model-specific sequence length, 4096 for llama 2, 8192 for mistral and llama 3
export GROUPSIZE=8
# ^-- 16 for 1.x bits per weight, 8 for 2.x bits per weight

export BLOCK_CLASS_NAME=LlamaDecoderLayer

# configure initial aqlm calibration
export NUM_CALIBRATION_SEQUENCES=2048
export CALIBRATION_DATASET_NAME=pajama
export CALIBRATED_MODEL_SAVE_PATH=./saved_aqlm_model

# configure finetuning
export FINETUNING_DATASET=togethercomputer/RedPajama-Data-V2
export DATACONFIG=sample-10B
export DATASPLIT=train
export TOKENIZED_DATASET_SAVE_PATH=./redpajama_tokenized_llama3
export FINETUNED_MODEL_SAVE_PATH=./saved_finetuned_model
export FINAL_MODEL_SAVE_PATH=./saved_final_model
export HF_EXPORT_PATH=./saved_hf_model


# 1. Initial calibration: run AQLM without global finetuning

python main.py \
    $MODEL_PATH \
    $CALIBRATION_DATASET_NAME \
    --nsamples=$NUM_CALIBRATION_SEQUENCES \
    --val_size=256 \
    --model_seqlen=$SEQLEN \
    --num_codebooks=1 \
    --nbits_per_codebook=16 \
    --out_group_size=1 \
    --in_group_size=$GROUPSIZE \
    --beam_size=1 \
    --relative_mse_tolerance=0.01 \
    --max_epochs=100 \
    --finetune_lr=1e-5 \
    --finetune_adam_beta1=0.90 \
    --finetune_adam_beta2=0.95 \
    --finetune_keep_best \
    --finetune_batch_size=32 \
    --local_batch_size=2 \
    --finetune_max_epochs=10 \
    --finetune_early_stop=3 \
    --offload_activations \
    --save $CALIBRATED_MODEL_SAVE_PATH \
    --resume \
    --wandb

# 1. prepare tokenized dataset for finetuning
git checkout pv-tuning
CUDA_VISIBLE_DEVICES=0 OMP_NUM_THREADS=16 torchrun --master-port 3456 --nproc-per-node=1 finetune_fsdp.py \
  --base_model meta-llama/Llama-2-7b-hf --quantized_model ./doesnt_matter --block_type doesnt_matter \
  --dataset_name=$FINETUNING_DATASET --dataset_config_name $DATACONFIG --split $DATASPLIT \
  --preprocessing_num_workers=64 --download_num_workers=1 \
  --cache_dir=./cache_dir --trust_remote_code --model_seqlen=$SEQLEN --preprocessing_chunk_length 100000 \
  --save_dataset_and_exit $TOKENIZED_DATASET_SAVE_PATH

# 2. finetune on the tokenized dataset

torchrun --nproc-per-node=$NUM_GPUS finetune_fsdp.py \
    --base_model $MODEL_PATH --code_dtype=uint16 --wandb --monkeypatch_old_pickle --quantized_model $CALIBRATED_MODEL_SAVE_PATH \
    --model_seqlen=$SEQLEN --block_type $BLOCK_CLASS_NAME \
    --gradient_checkpointing --dtype bfloat16 --amp_dtype bfloat16 \
    --dataset_name=$TOKENIZED_DATASET_PATH --split $DATASPLIT \
    --preprocessing_chunk_length 100000 --cache_dir=./cache --trust_remote_code \
    --lr 3e-6 --adam_beta1 0.9 --adam_beta2 0.98 --batch_size=32 --microbatch_size=1 --max_epochs 1  \
    --print_every_steps=10 --save_every_steps 100 --eval_every_steps=100 --keep_best_model \
    --save $FINETUNED_MODEL_SAVE_PATH


# 3. export to HF
python convert_legacy_model_format.py --base_model $MODEL_PATH \
    --quantized_model=$CALIBRATED_MODEL_SAVE_PATH \
    --p_finetuned_state_dict $FINETUNED_MODEL_SAVE_PATH/best_model_state_dict.pt \
    --code_dtype int32  --load_dtype auto --monkeypatch_old_pickle \
    --save $FINAL_MODEL_SAVE_PATH

python convert_to_hf.py $MODEL_PATH  $FINAL_MODEL_SAVE_PATH $HF_EXPORT_PATH --save_safetensors
```

</details>

**Comment by justheuristic** [comment]
Having written this sample script, I now realize that it is unreasonably complicated.

I can walk you through the process of quantizing these models - over a quick googlemeet / zoom call at any time you prefer. No pressure if you don't like zoom calls. 

One possible use case would be quantizing this together: https://github.com/Vahe1994/AQLM/issues/94
